name: ZMK Build Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Init west
        run: west init -l config

      - name: Update west
        run: west update

      - name: Build firmware
        run: |
          west build -s zmk/app -b nrf52840dongle_nrf52840 -- -DSHIELD=dongle_display
